//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTruongDaiHoc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyDaiHocEntities : DbContext
    {
        public QuanLyDaiHocEntities()
            : base("name=QuanLyDaiHocEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_CapHocBong> tb_CapHocBong { get; set; }
        public virtual DbSet<tb_ChiTietDanhGiaRL> tb_ChiTietDanhGiaRL { get; set; }
        public virtual DbSet<tb_ChiTietKhoaHoc> tb_ChiTietKhoaHoc { get; set; }
        public virtual DbSet<tb_ChiTietLichThi> tb_ChiTietLichThi { get; set; }
        public virtual DbSet<tb_ChiTietNoiDungKhaoSat> tb_ChiTietNoiDungKhaoSat { get; set; }
        public virtual DbSet<tb_ChiTietNoiDungRenLuyen> tb_ChiTietNoiDungRenLuyen { get; set; }
        public virtual DbSet<tb_ChiTietTotNghiep> tb_ChiTietTotNghiep { get; set; }
        public virtual DbSet<tb_Chuongtrinhdaotao> tb_Chuongtrinhdaotao { get; set; }
        public virtual DbSet<tb_DangKyMonHoc> tb_DangKyMonHoc { get; set; }
        public virtual DbSet<tb_DangKyNghiPhep> tb_DangKyNghiPhep { get; set; }
        public virtual DbSet<tb_DanhGiaRL> tb_DanhGiaRL { get; set; }
        public virtual DbSet<tb_DanhSachTotNghiep> tb_DanhSachTotNghiep { get; set; }
        public virtual DbSet<tb_GDQPAN> tb_GDQPAN { get; set; }
        public virtual DbSet<tb_GiangVien> tb_GiangVien { get; set; }
        public virtual DbSet<tb_GiaoDucTheChatLT> tb_GiaoDucTheChatLT { get; set; }
        public virtual DbSet<tb_GiaoDucTheChatTH> tb_GiaoDucTheChatTH { get; set; }
        public virtual DbSet<tb_GiayChungNhan> tb_GiayChungNhan { get; set; }
        public virtual DbSet<tb_HeDaoTao> tb_HeDaoTao { get; set; }
        public virtual DbSet<tb_HocBong> tb_HocBong { get; set; }
        public virtual DbSet<tb_HocKi> tb_HocKi { get; set; }
        public virtual DbSet<tb_HocPhiTC> tb_HocPhiTC { get; set; }
        public virtual DbSet<tb_KhaoSatKhoaHoc> tb_KhaoSatKhoaHoc { get; set; }
        public virtual DbSet<tb_KhoaHoc> tb_KhoaHoc { get; set; }
        public virtual DbSet<tb_KhoaVien> tb_KhoaVien { get; set; }
        public virtual DbSet<tb_KyNang> tb_KyNang { get; set; }
        public virtual DbSet<tb_LichDangKyMon> tb_LichDangKyMon { get; set; }
        public virtual DbSet<tb_LichDanhGiaRL> tb_LichDanhGiaRL { get; set; }
        public virtual DbSet<tb_LoaiPhong> tb_LoaiPhong { get; set; }
        public virtual DbSet<tb_LopHoc> tb_LopHoc { get; set; }
        public virtual DbSet<tb_MinhChungDGRL> tb_MinhChungDGRL { get; set; }
        public virtual DbSet<tb_Monhoc> tb_Monhoc { get; set; }
        public virtual DbSet<tb_MonHocCoTheDay> tb_MonHocCoTheDay { get; set; }
        public virtual DbSet<tb_Nganh> tb_Nganh { get; set; }
        public virtual DbSet<tb_NgoaiNguKhongChuyen> tb_NgoaiNguKhongChuyen { get; set; }
        public virtual DbSet<tb_NoiDungKhaoSat> tb_NoiDungKhaoSat { get; set; }
        public virtual DbSet<tb_NoiDungRenLuyen> tb_NoiDungRenLuyen { get; set; }
        public virtual DbSet<tb_PhongHoc> tb_PhongHoc { get; set; }
        public virtual DbSet<tb_QuanTri> tb_QuanTri { get; set; }
        public virtual DbSet<tb_QuyTacTinhDiem> tb_QuyTacTinhDiem { get; set; }
        public virtual DbSet<tb_SinhVien> tb_SinhVien { get; set; }
        public virtual DbSet<tb_TaiKhoan> tb_TaiKhoan { get; set; }
        public virtual DbSet<tb_ThongBao> tb_ThongBao { get; set; }
        public virtual DbSet<tb_ThongTinCaNhan> tb_ThongTinCaNhan { get; set; }
        public virtual DbSet<tb_ThongTinNgayThi> tb_ThongTinNgayThi { get; set; }
        public virtual DbSet<tb_YeuCauGiayChungNhan> tb_YeuCauGiayChungNhan { get; set; }
    }
}
