//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTruongDaiHoc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tb_Chuongtrinhdaotao
    {
        [DisplayName("ID")]
        public int ID { get; set; }

        [DisplayName("Mã ngành")]
        public Nullable<int> MaNganh { get; set; }

        [DisplayName("Mã môn học")]
        public Nullable<int> MaMonHoc { get; set; }

        [DisplayName("Bắt buộc")]
        public Nullable<bool> BatBuoc { get; set; }

        [DisplayName("Học kì")]
        public Nullable<int> Hocki { get; set; }

        [DisplayName("Năm")]
        public Nullable<int> Nam { get; set; }

        public virtual tb_Monhoc tb_Monhoc { get; set; }
        public virtual tb_Nganh tb_Nganh { get; set; }
    }
}
