//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTruongDaiHoc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tb_ChiTietNoiDungRenLuyen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_ChiTietNoiDungRenLuyen()
        {
            this.tb_ChiTietDanhGiaRL = new HashSet<tb_ChiTietDanhGiaRL>();
        }

        [DisplayName("ID")]
        public int ID { get; set; }

        [DisplayName("ID Nội dung Rèn luyện")]
        public int ID_NoiDungRL { get; set; }

        [DisplayName("Mã Chi tiết")]
        public string MaChiTiet { get; set; }

        [DisplayName("Tên Chi tiết")]
        public string TenChiTiet { get; set; }

        [DisplayName("Điểm Tối đa")]
        public Nullable<int> DiemToiDa { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ChiTietDanhGiaRL> tb_ChiTietDanhGiaRL { get; set; }
        public virtual tb_NoiDungRenLuyen tb_NoiDungRenLuyen { get; set; }
    }
}
