//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTruongDaiHoc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tb_ChiTietLichThi
    {
        [DisplayName("ID")]
        public int ID { get; set; }

        [DisplayName("Mã thông tin Ngày thi")]
        public Nullable<int> ID_ThongTinNgayThi { get; set; }

        [DisplayName("Mã Sinh viên")]
        public Nullable<int> ID_SinhVien { get; set; }

        public virtual tb_SinhVien tb_SinhVien { get; set; }
        public virtual tb_ThongTinNgayThi tb_ThongTinNgayThi { get; set; }
    }
}
