//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTruongDaiHoc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tb_ChiTietTotNghiep
    {
        [DisplayName("ID")]
        public int ID { get; set; }

        [DisplayName("Mã số Sinh viên")]
        public Nullable<int> ID_SinhVien { get; set; }

        [DisplayName("Điểm")]
        public Nullable<double> Diem { get; set; }

        [DisplayName("Xếp loại")]
        public string XepLoai { get; set; }

        public virtual tb_SinhVien tb_SinhVien { get; set; }
    }
}
