//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTruongDaiHoc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tb_CapHocBong
    {

        [DisplayName("Mã số")]
        public int ID { get; set; }

        public Nullable<int> ID_HocBong { get; set; } // Mã số Học bổng

        [DisplayName("Mã số Sinh viên")]
        public int ID_SinhVien { get; set; }

        [DisplayName("Học kì")]
        public Nullable<int> HocKi { get; set; }

        [DisplayName("Năm")]
        public Nullable<int> Nam { get; set; }

        public virtual tb_HocBong tb_HocBong { get; set; }
        public virtual tb_SinhVien tb_SinhVien { get; set; }
    }
}
