//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTruongDaiHoc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tb_ChiTietDanhGiaRL
    {
        [DisplayName("Mã số")]
        public int ID { get; set; }

        [DisplayName("Mã số Đánh giá Rèn luyện")]
        public Nullable<int> ID_DanhGiaRL { get; set; }

        [DisplayName("Mã số Chi tiết Nội dung")]
        public Nullable<int> ID_ChiTietNoiDung { get; set; }

        [DisplayName("Điểm SV Đánh giá")]
        public Nullable<int> DiemSVDanhGia { get; set; }

        [DisplayName("Điểm GV Đánh giá")]
        public Nullable<int> DiemGVDanhGia { get; set; }

        [DisplayName("Điểm QT Đánh giá")]
        public Nullable<int> DiemQTDanhGia { get; set; }

        public virtual tb_ChiTietNoiDungRenLuyen tb_ChiTietNoiDungRenLuyen { get; set; }
        public virtual tb_DanhGiaRL tb_DanhGiaRL { get; set; }
    }
}
