//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTruongDaiHoc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tb_ChiTietNoiDungKhaoSat
    {
        [DisplayName("ID")]
        public int ID { get; set; }

        [DisplayName("Mã Nội dung")]
        public Nullable<int> MaNoiDung { get; set; }

        [DisplayName("Mã Chi tiết")]
        public string MaChiTiet { get; set; }

        [DisplayName("Tên Chi tiết")]
        public string TenChiTiet { get; set; }

        public virtual tb_NoiDungKhaoSat tb_NoiDungKhaoSat { get; set; }
    }
}
