//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTruongDaiHoc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tb_ChiTietKhoaHoc
    {
        [DisplayName("ID")]
        public int ID { get; set; }

        [DisplayName("Mã Khóa học")]
        public Nullable<int> ID_KhoaHoc { get; set; }

        [DisplayName("Mã Phòng học")]
        public Nullable<int> ID_PhongHoc { get; set; }

        [DisplayName("Mã Ngày")]
        public Nullable<System.DateTime> Ngay { get; set; }

        [DisplayName("Mã Tiết bắt đầu")]
        public Nullable<int> TietBatDau { get; set; }

        [DisplayName("Mã Tiết kết thúc")]
        public Nullable<int> TietKetThuc { get; set; }

        [DisplayName("Mã Số tiết")]
        public Nullable<int> soTiet { get; set; }

        public virtual tb_KhoaHoc tb_KhoaHoc { get; set; }
        public virtual tb_PhongHoc tb_PhongHoc { get; set; }
    }
}
