//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTruongDaiHoc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tb_DanhSachTotNghiep
    {
        [DisplayName("ID")]
        public int ID { get; set; }

        [DisplayName("Mã Danh sách")]
        public string MaDanhSach { get; set; }

        [DisplayName("Tên Danh sách")]
        public string TenDanhSach { get; set; }

        [DisplayName("Đợt")]
        public Nullable<int> Dot { get; set; }

        [DisplayName("Thời gian")]
        public Nullable<System.DateTime> ThoiGian { get; set; }
    }
}
