//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTruongDaiHoc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tb_DanhGiaRL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_DanhGiaRL()
        {
            this.tb_ChiTietDanhGiaRL = new HashSet<tb_ChiTietDanhGiaRL>();
            this.tb_MinhChungDGRL = new HashSet<tb_MinhChungDGRL>();
        }

        [DisplayName("ID")]
        public int ID { get; set; }

        [DisplayName("ID Sinh viên")]
        public Nullable<int> ID_SinhVien { get; set; }

        [DisplayName("ID Giảng viên")]
        public Nullable<int> ID_GiangVien { get; set; }

        [DisplayName("ID Quản trị")]
        public Nullable<int> ID_QuanTri { get; set; }

        [DisplayName("Tổng điểm")]
        public Nullable<int> TongDiem { get; set; }

        [DisplayName("Tổng điểm tối đa")]
        public Nullable<int> TongToiDa { get; set; }

        [DisplayName("Xếp loại")]
        public string XepLoai { get; set; }

        [DisplayName("Ghi chú")]
        public string GhiChu { get; set; }

        [DisplayName("Học kì")]
        public Nullable<int> HocKi { get; set; }

        [DisplayName("Năm")]
        public Nullable<int> Nam { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ChiTietDanhGiaRL> tb_ChiTietDanhGiaRL { get; set; }
        public virtual tb_GiangVien tb_GiangVien { get; set; }
        public virtual tb_QuanTri tb_QuanTri { get; set; }
        public virtual tb_SinhVien tb_SinhVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_MinhChungDGRL> tb_MinhChungDGRL { get; set; }
    }
}
