//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTruongDaiHoc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tb_DangKyNghiPhep
    {
        [DisplayName("ID")]
        public int ID { get; set; }

        [DisplayName("ID Giảng viên")]
        public Nullable<int> ID_GiangVien { get; set; }

        [DisplayName("Ngày nghỉ")]
        public Nullable<System.DateTime> NgayNghi { get; set; }

        [DisplayName("Lý do")]
        public string LyDo { get; set; }

        [DisplayName("Trạng thái")]
        public Nullable<int> TrangThai { get; set; }

        [DisplayName("Ngày gửi")]
        public Nullable<System.DateTime> NgayGui { get; set; }

        [DisplayName("ID Quản trị")]
        public Nullable<int> ID_QuanTri { get; set; }

        [DisplayName("Phản hồi")]
        public string PhanHoi { get; set; }

        [DisplayName("Ngày duyệt")]
        public Nullable<System.DateTime> NgayDuyet { get; set; }

        public virtual tb_GiangVien tb_GiangVien { get; set; }
        public virtual tb_QuanTri tb_QuanTri { get; set; }
    }
}
