//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTruongDaiHoc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tb_DangKyMonHoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_DangKyMonHoc()
        {
            this.tb_KhaoSatKhoaHoc = new HashSet<tb_KhaoSatKhoaHoc>();
        }

        [DisplayName("ID")]
        public int ID { get; set; }

        [DisplayName("ID Khóa học")]
        public int ID_KhoaHoc { get; set; }

        [DisplayName("ID Môn học")]
        public Nullable<int> ID_MonHoc { get; set; }

        [DisplayName("ID Sinh viên")]
        public int ID_SinhVien { get; set; }

        [DisplayName("Học kì")]
        public Nullable<int> HocKi { get; set; }

        [DisplayName("Năm")]
        public Nullable<int> Nam { get; set; }

        [DisplayName("Điểm Kiểm tra định kỳ")]
        public Nullable<double> diemKTDK { get; set; }

        [DisplayName("Điểm Kiểm tra học phần")]
        public Nullable<double> diemKTHP { get; set; }

        [DisplayName("Kết quả")]
        public Nullable<bool> KetQua { get; set; }

        public virtual tb_KhoaHoc tb_KhoaHoc { get; set; }
        public virtual tb_Monhoc tb_Monhoc { get; set; }
        public virtual tb_SinhVien tb_SinhVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_KhaoSatKhoaHoc> tb_KhaoSatKhoaHoc { get; set; }
    }
}
