//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTruongDaiHoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_GiaoDucTheChatLT
    {
        public int ID_MonHoc { get; set; }
    
        public virtual tb_Monhoc tb_Monhoc { get; set; }
    }
}
