//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTruongDaiHoc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tb_GiangVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_GiangVien()
        {
            this.tb_DangKyNghiPhep = new HashSet<tb_DangKyNghiPhep>();
            this.tb_DanhGiaRL = new HashSet<tb_DanhGiaRL>();
            this.tb_KhoaHoc = new HashSet<tb_KhoaHoc>();
            this.tb_LopHoc = new HashSet<tb_LopHoc>();
            this.tb_MonHocCoTheDay = new HashSet<tb_MonHocCoTheDay>();
            this.tb_ThongTinNgayThi = new HashSet<tb_ThongTinNgayThi>();
            this.tb_ThongTinNgayThi1 = new HashSet<tb_ThongTinNgayThi>();
        }

        [DisplayName("ID")]
        public int ID { get; set; }

        [DisplayName("Mã Giảng viên")]
        public string MaGiangVien { get; set; }

        [DisplayName("Trình độ")]
        public string TrinhDo { get; set; }

        [DisplayName("Chương trình giảng dạy")]
        public string ChuongTrinhGiangDay { get; set; }

        [DisplayName("ID Thông tin cá nhân")]
        public Nullable<int> ID_ThongTinCaNhan { get; set; }

        [DisplayName("ID Tài khoản")]
        public Nullable<int> ID_TaiKhoan { get; set; }

        [DisplayName("ID Chuyên ngành")]
        public Nullable<int> ID_ChuyenNganh { get; set; }

        [DisplayName("Trạng thái")]
        public Nullable<bool> TrangThai { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_DangKyNghiPhep> tb_DangKyNghiPhep { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_DanhGiaRL> tb_DanhGiaRL { get; set; }
        public virtual tb_Nganh tb_Nganh { get; set; }
        public virtual tb_TaiKhoan tb_TaiKhoan { get; set; }
        public virtual tb_ThongTinCaNhan tb_ThongTinCaNhan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_KhoaHoc> tb_KhoaHoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_LopHoc> tb_LopHoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_MonHocCoTheDay> tb_MonHocCoTheDay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ThongTinNgayThi> tb_ThongTinNgayThi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ThongTinNgayThi> tb_ThongTinNgayThi1 { get; set; }
    }
}
