//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTruongDaiHoc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tb_HocKi
    {
        [DisplayName("ID")]
        public int ID { get; set; }

        [DisplayName("Thời gian")]
        public Nullable<int> ThoiGian { get; set; }

        [DisplayName("Học kỳ tối đa")]
        public Nullable<int> HocKiToiDa { get; set; }
    }
}
