//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTruongDaiHoc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tb_HocPhiTC
    {
        [DisplayName("ID Hệ đào tạo")]
        public int ID_HeDaoTao { get; set; }

        [DisplayName("ID Ngành")]
        public int ID_Nganh { get; set; }

        [DisplayName("Giá")]
        public decimal Gia { get; set; }

        public virtual tb_HeDaoTao tb_HeDaoTao { get; set; }
        public virtual tb_Nganh tb_Nganh { get; set; }
    }
}
