//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTruongDaiHoc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tb_KhoaHoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_KhoaHoc()
        {
            this.tb_ChiTietKhoaHoc = new HashSet<tb_ChiTietKhoaHoc>();
            this.tb_DangKyMonHoc = new HashSet<tb_DangKyMonHoc>();
            this.tb_ThongTinNgayThi = new HashSet<tb_ThongTinNgayThi>();
        }

        [DisplayName("ID")]
        public int ID { get; set; }

        [DisplayName("Mã Khóa học")]
        public string MaKhoaHoc { get; set; }

        [DisplayName("ID Môn học")]
        public int ID_MonHoc { get; set; }

        [DisplayName("ID Hệ đào tạo")]
        public Nullable<int> ID_HeDaoTao { get; set; }

        [DisplayName("ID Giảng viên")]
        public int ID_GiangVien { get; set; }

        [DisplayName("Số lượng yêu cầu")]
        public int SoLuongYeuCau { get; set; }

        [DisplayName("Số lượng hiện tại")]
        public int SoLuongHienTai { get; set; }

        [DisplayName("Ngày mở")]
        public Nullable<System.DateTime> NgayMo { get; set; }

        [DisplayName("Trạng thái")]
        public Nullable<int> TrangThai { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ChiTietKhoaHoc> tb_ChiTietKhoaHoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_DangKyMonHoc> tb_DangKyMonHoc { get; set; }
        public virtual tb_GiangVien tb_GiangVien { get; set; }
        public virtual tb_HeDaoTao tb_HeDaoTao { get; set; }
        public virtual tb_Monhoc tb_Monhoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ThongTinNgayThi> tb_ThongTinNgayThi { get; set; }
    }
}
