//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTruongDaiHoc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tb_KhoaVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_KhoaVien()
        {
            this.tb_Nganh = new HashSet<tb_Nganh>();
        }

        [DisplayName("ID")]
        public int ID { get; set; }

        [DisplayName("Mã Khoa viện")]
        public string MaKhoaVien { get; set; }

        [DisplayName("Tên Khoa viện")]
        public string TenKhoaVien { get; set; }

        [DisplayName("Mô tả")]
        public string Mota { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Nganh> tb_Nganh { get; set; }
    }
}
