//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTruongDaiHoc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tb_KhaoSatKhoaHoc
    {
        [DisplayName("ID")]
        public int ID { get; set; }

        [DisplayName("ID Đăng ký môn học")]
        public Nullable<int> ID_DangKyMonHoc { get; set; }

        [DisplayName("ID Sinh viên")]
        public Nullable<int> ID_SinhVien { get; set; }

        [DisplayName("Trạng thái")]
        public Nullable<bool> TrangThai { get; set; }

        public virtual tb_DangKyMonHoc tb_DangKyMonHoc { get; set; }
        public virtual tb_SinhVien tb_SinhVien { get; set; }
    }
}
