//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTruongDaiHoc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tb_KyNang
    {
        [DisplayName("ID Môn học")]
        public int ID_MonHoc { get; set; }

        [DisplayName("Cấp")]
        public Nullable<int> Cap { get; set; }

        public virtual tb_Monhoc tb_Monhoc { get; set; }
    }
}
