//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTruongDaiHoc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tb_LichDangKyMon
    {
        [DisplayName("ID")]
        public int ID { get; set; }

        [DisplayName("Thời gian Bắt đầu")]
        public Nullable<System.DateTime> TGBatDau { get; set; }

        [DisplayName("Thời gian Kết thúc")]
        public Nullable<System.DateTime> TGKetThuc { get; set; }

        [DisplayName("Học kỳ")]
        public Nullable<int> HocKi { get; set; }

        [DisplayName("Năm")]
        public Nullable<int> Nam { get; set; }
    }
}
