//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTruongDaiHoc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tb_LichDanhGiaRL
    {
        [DisplayName("ID")]
        public int ID { get; set; }

        [DisplayName("Ngày Mở")]
        public Nullable<System.DateTime> NgayMo { get; set; }

        [DisplayName("Ngày Đóng")]
        public Nullable<System.DateTime> NgayDong { get; set; }
    }
}
