//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTruongDaiHoc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tb_LopHoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_LopHoc()
        {
            this.tb_SinhVien = new HashSet<tb_SinhVien>();
        }

        [DisplayName("ID")]
        public int ID { get; set; }

        [DisplayName("Mã Lớp học")]
        public string MaLopHoc { get; set; }

        [DisplayName("ID Ngành")]
        public int ID_Nganh { get; set; }

        [DisplayName("ID Hệ đào tạo")]
        public Nullable<int> ID_HeDaoTao { get; set; }

        [DisplayName("ID Cố vấn")]
        public Nullable<int> ID_CoVan { get; set; }

        [DisplayName("Số lượng")]
        public Nullable<int> SoLuong { get; set; }

        public virtual tb_GiangVien tb_GiangVien { get; set; }
        public virtual tb_HeDaoTao tb_HeDaoTao { get; set; }
        public virtual tb_Nganh tb_Nganh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_SinhVien> tb_SinhVien { get; set; }
    }
}
