//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTruongDaiHoc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tb_MonHocCoTheDay
    {
        [DisplayName("ID")]
        public int ID { get; set; }

        [DisplayName("ID Giảng viên")]
        public Nullable<int> ID_GiangVien { get; set; }

        [DisplayName("ID Môn học")]
        public Nullable<int> ID_MonHoc { get; set; }
        public virtual tb_GiangVien tb_GiangVien { get; set; }
        public virtual tb_Monhoc tb_Monhoc { get; set; }
    }
}
