//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTruongDaiHoc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tb_Monhoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Monhoc()
        {
            this.tb_Chuongtrinhdaotao = new HashSet<tb_Chuongtrinhdaotao>();
            this.tb_DangKyMonHoc = new HashSet<tb_DangKyMonHoc>();
            this.tb_KhoaHoc = new HashSet<tb_KhoaHoc>();
            this.tb_MonHocCoTheDay = new HashSet<tb_MonHocCoTheDay>();
        }

        [DisplayName("ID")]
        public int ID { get; set; }

        [DisplayName("Mã Môn học")]
        public string MaMonHoc { get; set; }

        [DisplayName("Tên Môn học")]
        public string TenMonHoc { get; set; }

        [DisplayName("Chuyên Ngành")]
        public Nullable<int> ChuyenNganh { get; set; }

        [DisplayName("Loại Môn học")]
        public Nullable<int> LoaiMonHoc { get; set; }

        [DisplayName("Số tín chỉ")]
        public Nullable<int> SoTC { get; set; }

        [DisplayName("Số tiết")]
        public Nullable<int> SoTiet { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Chuongtrinhdaotao> tb_Chuongtrinhdaotao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_DangKyMonHoc> tb_DangKyMonHoc { get; set; }
        public virtual tb_GDQPAN tb_GDQPAN { get; set; }
        public virtual tb_GiaoDucTheChatLT tb_GiaoDucTheChatLT { get; set; }
        public virtual tb_GiaoDucTheChatTH tb_GiaoDucTheChatTH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_KhoaHoc> tb_KhoaHoc { get; set; }
        public virtual tb_KyNang tb_KyNang { get; set; }
        public virtual tb_Nganh tb_Nganh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_MonHocCoTheDay> tb_MonHocCoTheDay { get; set; }
        public virtual tb_NgoaiNguKhongChuyen tb_NgoaiNguKhongChuyen { get; set; }
    }
}
