//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTruongDaiHoc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tb_NoiDungKhaoSat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_NoiDungKhaoSat()
        {
            this.tb_ChiTietNoiDungKhaoSat = new HashSet<tb_ChiTietNoiDungKhaoSat>();
        }

        [DisplayName("ID")]
        public int ID { get; set; }

        [DisplayName("Mã Nội dung")]
        public string MaNoiDung { get; set; }

        [DisplayName("Tên Nội dung")]
        public string TenNoiDung { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ChiTietNoiDungKhaoSat> tb_ChiTietNoiDungKhaoSat { get; set; }
    }
}
