//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTruongDaiHoc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tb_Nganh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Nganh()
        {
            this.tb_Chuongtrinhdaotao = new HashSet<tb_Chuongtrinhdaotao>();
            this.tb_GiangVien = new HashSet<tb_GiangVien>();
            this.tb_HocPhiTC = new HashSet<tb_HocPhiTC>();
            this.tb_LopHoc = new HashSet<tb_LopHoc>();
            this.tb_Monhoc = new HashSet<tb_Monhoc>();
            this.tb_SinhVien = new HashSet<tb_SinhVien>();
        }

        [DisplayName("ID")]
        public int ID { get; set; }

        [DisplayName("Mã Ngành")]
        public string MaNganh { get; set; }

        [DisplayName("Tên Ngành")]
        public string TenNganh { get; set; }

        [DisplayName("Mã Khoa viện")]
        public Nullable<int> MaKhoaVien { get; set; }

        [DisplayName("Năm Đào tạo")]
        public Nullable<double> NamDaotao { get; set; }

        [DisplayName("Mô tả")]
        public string Mota { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Chuongtrinhdaotao> tb_Chuongtrinhdaotao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_GiangVien> tb_GiangVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_HocPhiTC> tb_HocPhiTC { get; set; }
        public virtual tb_KhoaVien tb_KhoaVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_LopHoc> tb_LopHoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Monhoc> tb_Monhoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_SinhVien> tb_SinhVien { get; set; }
    }
}
