//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTruongDaiHoc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tb_PhongHoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_PhongHoc()
        {
            this.tb_ChiTietKhoaHoc = new HashSet<tb_ChiTietKhoaHoc>();
            this.tb_ThongTinNgayThi = new HashSet<tb_ThongTinNgayThi>();
        }

        [DisplayName("ID")]
        public int ID { get; set; }

        [DisplayName("Mã Phòng học")]
        public string MaPhongHoc { get; set; }

        [DisplayName("Vị trí")]
        public string ViTri { get; set; }

        [DisplayName("ID Loại Phòng")]
        public Nullable<int> ID_LoaiPhong { get; set; }

        [DisplayName("Sức chứa")]
        public int SucChua { get; set; }

        [DisplayName("Trạng thái")]
        public bool TrangThai { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ChiTietKhoaHoc> tb_ChiTietKhoaHoc { get; set; }
        public virtual tb_LoaiPhong tb_LoaiPhong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ThongTinNgayThi> tb_ThongTinNgayThi { get; set; }
    }
}
