//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTruongDaiHoc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tb_SinhVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_SinhVien()
        {
            this.tb_CapHocBong = new HashSet<tb_CapHocBong>();
            this.tb_ChiTietLichThi = new HashSet<tb_ChiTietLichThi>();
            this.tb_ChiTietTotNghiep = new HashSet<tb_ChiTietTotNghiep>();
            this.tb_DangKyMonHoc = new HashSet<tb_DangKyMonHoc>();
            this.tb_DanhGiaRL = new HashSet<tb_DanhGiaRL>();
            this.tb_KhaoSatKhoaHoc = new HashSet<tb_KhaoSatKhoaHoc>();
            this.tb_YeuCauGiayChungNhan = new HashSet<tb_YeuCauGiayChungNhan>();
        }

        [DisplayName("ID")]
        public int ID { get; set; }

        [DisplayName("Mã Sinh viên")]
        public string MaSinhVien { get; set; }

        [DisplayName("Số TC Tích lũy")]
        public int SoTC_TichLuy { get; set; }

        [DisplayName("Giáo dục thể chất LT")]
        public bool GiaoDucTheChat_LT { get; set; }

        [DisplayName("Giáo dục thể chất TH")]
        public bool GiaoDucTheChat_TH { get; set; }

        [DisplayName("GDQPAN")]
        public bool GDQPAN { get; set; }

        [DisplayName("Số Môn F")]
        public int SoMon_F { get; set; }

        [DisplayName("Số Cấp Ngoại ngữ")]
        public int SoCap_NgoaiNgu { get; set; }

        [DisplayName("Kỹ năng")]
        public Nullable<bool> KyNang { get; set; }

        [DisplayName("Điểm Tích lũy")]
        public Nullable<double> DiemTichLuy { get; set; }

        [DisplayName("Tốt nghiệp")]
        public bool TotNghiep { get; set; }

        [DisplayName("Trạng thái")]
        public Nullable<bool> TrangThai { get; set; }

        [DisplayName("ID Thông tin Cá nhân")]
        public Nullable<int> ID_ThongTinCaNhan { get; set; }

        [DisplayName("ID Tài khoản")]
        public Nullable<int> ID_TaiKhoan { get; set; }

        [DisplayName("ID Chuyên Ngành")]
        public Nullable<int> ID_ChuyenNganh { get; set; }

        [DisplayName("ID Hệ Đào tạo")]
        public Nullable<int> ID_HeDaoTao { get; set; }

        [DisplayName("ID Lớp học")]
        public Nullable<int> ID_LopHoc { get; set; }

        [DisplayName("Ngày Nhập học")]
        public Nullable<System.DateTime> NgayNhapHoc { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_CapHocBong> tb_CapHocBong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ChiTietLichThi> tb_ChiTietLichThi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ChiTietTotNghiep> tb_ChiTietTotNghiep { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_DangKyMonHoc> tb_DangKyMonHoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_DanhGiaRL> tb_DanhGiaRL { get; set; }
        public virtual tb_HeDaoTao tb_HeDaoTao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_KhaoSatKhoaHoc> tb_KhaoSatKhoaHoc { get; set; }
        public virtual tb_LopHoc tb_LopHoc { get; set; }
        public virtual tb_Nganh tb_Nganh { get; set; }
        public virtual tb_TaiKhoan tb_TaiKhoan { get; set; }
        public virtual tb_ThongTinCaNhan tb_ThongTinCaNhan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_YeuCauGiayChungNhan> tb_YeuCauGiayChungNhan { get; set; }
    }
}
