//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTruongDaiHoc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tb_ThongTinCaNhan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_ThongTinCaNhan()
        {
            this.tb_GiangVien = new HashSet<tb_GiangVien>();
            this.tb_QuanTri = new HashSet<tb_QuanTri>();
            this.tb_SinhVien = new HashSet<tb_SinhVien>();
        }

        [DisplayName("ID")]
        public int ID { get; set; }

        [DisplayName("Họ tên")]
        public string Hoten { get; set; }

        [DisplayName("Ngày sinh")]
        public System.DateTime NgaySinh { get; set; }

        [DisplayName("Số điện thoại")]
        public string SDT { get; set; }

        [DisplayName("Địa chỉ")]
        public string DiaChi { get; set; }

        [DisplayName("Email 1")]
        public string Email_1 { get; set; }

        [DisplayName("Email 2")]
        public string Email_2 { get; set; }

        [DisplayName("Số CCCD")]
        public string So_CCCD { get; set; }

        [DisplayName("Dân tộc")]
        public string DanToc { get; set; }

        [DisplayName("Giới tính")]
        public bool GioiTinh { get; set; }

        [DisplayName("Ảnh")]
        public string Anh { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_GiangVien> tb_GiangVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_QuanTri> tb_QuanTri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_SinhVien> tb_SinhVien { get; set; }
    }
}
