//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTruongDaiHoc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tb_ThongBao
    {
        [DisplayName("ID")]
        public int ID { get; set; }

        [DisplayName("ID Quản trị")]
        public int ID_QuanTri { get; set; }

        [DisplayName("Tiêu đề")]
        public string TieuDe { get; set; }

        [DisplayName("Nội dung")]
        public string NoiDung { get; set; }

        [DisplayName("Đối tượng nhận TB")]
        public int DoiTuongNhanTB { get; set; }

        [DisplayName("Ngày gửi")]
        public Nullable<System.DateTime> NgayGui { get; set; }

        public virtual tb_QuanTri tb_QuanTri { get; set; }
    }
}
