//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTruongDaiHoc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tb_ThongTinNgayThi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_ThongTinNgayThi()
        {
            this.tb_ChiTietLichThi = new HashSet<tb_ChiTietLichThi>();
        }

        [DisplayName("ID")]
        public int ID { get; set; }

        [DisplayName("ID Khóa học")]
        public Nullable<int> ID_KhoaHoc { get; set; }

        [DisplayName("ID Giám thị 1")]
        public Nullable<int> ID_GiamThi1 { get; set; }

        [DisplayName("ID Giám thị 2")]
        public Nullable<int> ID_GiamThi2 { get; set; }

        [DisplayName("Phòng thi")]
        public Nullable<int> PhongThi { get; set; }

        [DisplayName("Ngày thi")]
        public Nullable<System.DateTime> NgayThi { get; set; }

        [DisplayName("Giờ bắt đầu")]
        public string GioBatDau { get; set; }

        [DisplayName("Thời lượng")]
        public Nullable<int> ThoiLuong { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ChiTietLichThi> tb_ChiTietLichThi { get; set; }
        public virtual tb_GiangVien tb_GiangVien { get; set; }
        public virtual tb_GiangVien tb_GiangVien1 { get; set; }
        public virtual tb_KhoaHoc tb_KhoaHoc { get; set; }
        public virtual tb_PhongHoc tb_PhongHoc { get; set; }
    }
}
