//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTruongDaiHoc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tb_YeuCauGiayChungNhan
    {
        [DisplayName("ID")]
        public int ID { get; set; }

        [DisplayName("ID Giấy Chứng nhận")]
        public int ID_GiayChungNhan { get; set; }

        [DisplayName("ID Sinh viên")]
        public int ID_SinhVien { get; set; }

        [DisplayName("Thông tin yêu cầu")]
        public string ThongTinYeuCau { get; set; }

        [DisplayName("Trạng thái")]
        public int TrangThai { get; set; }

        [DisplayName("Phản hồi")]
        public string PhanHoi { get; set; }

        [DisplayName("ID Quản trị")]
        public Nullable<int> ID_QuanTri { get; set; }

        [DisplayName("Ngày yêu cầu")]
        public Nullable<System.DateTime> NgayYeuCau { get; set; }

        [DisplayName("Ngày duyệt")]
        public Nullable<System.DateTime> NgayDuyet { get; set; }

        public virtual tb_GiayChungNhan tb_GiayChungNhan { get; set; }
        public virtual tb_QuanTri tb_QuanTri { get; set; }
        public virtual tb_SinhVien tb_SinhVien { get; set; }
    }
}
